### ISSUE TITLE
Test failures with nosetests

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/unittest-ext#10]
```
Run nosetests, get failures:

======================================================================
ERROR: unittest2.test.test_case.TestEquality.test_eq
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File
"/var/tmp/portage/dev-python/unittest2-0.3.0/work/unittest2-0.3.0/unittest2/test
/support.py",
line 91, in test_eq
    for obj_1, obj_2 in self.eq_pairs:
AttributeError: 'TestEquality' object has no attribute 'eq_pairs'

======================================================================
ERROR: unittest2.test.test_case.TestEquality.test_ne
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File
"/var/tmp/portage/dev-python/unittest2-0.3.0/work/unittest2-0.3.0/unittest2/test
/support.py",
line 97, in test_ne
    for obj_1, obj_2 in self.ne_pairs:
AttributeError: 'TestEquality' object has no attribute 'ne_pairs'

======================================================================
ERROR: unittest2.test.test_case.TestHashing.test_hash
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File
"/var/tmp/portage/dev-python/unittest2-0.3.0/work/unittest2-0.3.0/unittest2/test
/support.py",
line 106, in test_hash
    for obj_1, obj_2 in self.eq_pairs:
AttributeError: 'TestHashing' object has no attribute 'eq_pairs'

======================================================================
ERROR: unittest2.test.test_suite.TestEquality.test_eq
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File
"/var/tmp/portage/dev-python/unittest2-0.3.0/work/unittest2-0.3.0/unittest2/test
/support.py",
line 91, in test_eq
    for obj_1, obj_2 in self.eq_pairs:
AttributeError: 'TestEquality' object has no attribute 'eq_pairs'

======================================================================
ERROR: unittest2.test.test_suite.TestEquality.test_ne
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib64/python2.6/site-packages/nose/case.py", line 186, in runTest
    self.test(*self.arg)
  File
"/var/tmp/portage/dev-python/unittest2-0.3.0/work/unittest2-0.3.0/unittest2/test
/support.py",
line 97, in test_ne
    for obj_1, obj_2 in self.ne_pairs:
AttributeError: 'TestEquality' object has no attribute 'ne_pairs'

----------------------------------------------------------------------
Ran 252 tests in 0.432s

FAILED (errors=5)

(Works fine with unit2 discover, of course.)
```

Original issue reported on code.google.com by `djc.ochtman` on 26 Mar 2010 at 5:48

**Comment by GoogleCodeExporter** [comment]
```
Hmmm... those aren't tests, they're mixin classes and don't inherit from 
TestCase.
Wonder they started failing now? I'll see if renaming them helps.
```

Original comment by `fuzzyman` on 26 Mar 2010 at 11:14

**Comment by GoogleCodeExporter** [comment]
```
Fixed in mercurial.
```

Original comment by `fuzzyman` on 26 Mar 2010 at 11:19

**Comment by GoogleCodeExporter** [comment]
Original comment by `fuzzyman` on 26 Mar 2010 at 11:20
- Changed state: **Fixed**
