### ISSUE TITLE
Custom version number class in setup.py breaks pip wheel

### ISSUE THREAD

**Issue by exarkun** [testing-cabal/unittest-ext#101]
```
$ pip wheel --no-dependencies --no-binary :all: unittest2                                                        
Collecting unittest2
  Using cached unittest2-1.1.0.tar.gz
Building wheels for collected packages: unittest2
  Running setup.py bdist_wheel for unittest2 ... error
  Complete output from command /tmp/unittest2-demo/bin/python -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-KoRJo1/unittest2/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp1d7zLEpip-wheel-:
  /tmp/unittest2-demo/local/lib/python2.7/site-packages/setuptools/dist.py:345: UserWarning: The version specified (<__main__.late_version instance at 0x7fc7b2581ef0>) is an invalid version, this may not work as expected with newer versions of setuptools, pip, and PyPI. Please see PEP 440 for more details.
    "details." % self.metadata.version
  running bdist_wheel
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-KoRJo1/unittest2/setup.py", line 87, in <module>
      setup(**params)
    File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
      dist.run_commands()
    File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python2.7/distutils/dist.py", line 971, in run_command
      cmd_obj.ensure_finalized()
    File "/usr/lib/python2.7/distutils/cmd.py", line 109, in ensure_finalized
      self.finalize_options()
    File "/tmp/unittest2-demo/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 108, in finalize_options
      self.data_dir = self.wheel_dist_name + '.data'
    File "/tmp/unittest2-demo/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 131, in wheel_dist_name
      safer_version(self.distribution.get_version())))
    File "/tmp/unittest2-demo/local/lib/python2.7/site-packages/wheel/bdist_wheel.py", line 47, in safer_version
      return safe_version(version).replace('-', '_')
    File "/tmp/unittest2-demo/local/lib/python2.7/site-packages/pkg_resources/__init__.py", line 1388, in safe_version
      return str(packaging.version.Version(version))
    File "/tmp/unittest2-demo/local/lib/python2.7/site-packages/pkg_resources/_vendor/packaging/version.py", line 200, in __init__
      match = self._regex.search(version)
  TypeError: expected string or buffer
  
  ----------------------------------------
  Failed building wheel for unittest2
  Running setup.py clean for unittest2
Failed to build unittest2
ERROR: Failed to build one or more wheels
$ pip --version
pip 9.0.1 from /tmp/unittest2-demo/local/lib/python2.7/site-packages (python 2.7)
```

Unfortunately some tool chains require building the wheel from source (even though there is a wheel on PyPI).  This problem breaks such tool chains and makes any project with a dependency (direct or transitive) on unittest2 unusable.

Also, the object passed for the `version` to `setup` clearly violates the interface.  It provokes a warning from setuptools pointing out that things may not work as expected - and, indeed, they do not.

**Comment by exarkun** [comment]
I was going to fix this and create a PR but the code on GitHub appears to be lagging far behind the code on hg.python.org.  I'm no longer confident this GitHub project is actually meaningful at all...

Hello, is anyone there?

**Comment by rbtcollins** [comment]
This is the appropriate repo for bugs; we'll be moving the code from hg sometime - unless you wanted to do that, we could give you the right access. The history of this repo is ... extended ;)

**Comment by rbtcollins** [comment]
What version of setuptools do you have there?

**Comment by exarkun** [comment]
The transcript in the issue description used setuptools 36.0.1
