### ISSUE TITLE
Handle filename extension in unit2 command-line.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/unittest-ext#18]
```
What steps will reproduce the problem?
1. Run unit2 with a test module where the name includes the file extension
2. unit2 test_example.py
3.

What is the expected output? What do you see instead?
I expected the test in test_example.py to run.  Instead I get the following 
traceback:

(trunk)cburns@unittest2 15:00:20 $ unit2 test_example.py
Traceback (most recent call last):
  File "/home/users/cburns/local/bin/unit2", line 8, in <module>
    main(module=None)
  File "/home/users/cburns/local/lib/python2.5/site-packages/unittest2/main.py", line 97, in __init__
    self.parseArgs(argv)
  File "/home/users/cburns/local/lib/python2.5/site-packages/unittest2/main.py", line 152, in parseArgs
    self.createTests()
  File "/home/users/cburns/local/lib/python2.5/site-packages/unittest2/main.py", line 161, in createTests
    self.module)
  File "/home/users/cburns/local/lib/python2.5/site-packages/unittest2/loader.py", line 146, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/home/users/cburns/local/lib/python2.5/site-packages/unittest2/loader.py", line 118, in loadTestsFromName
    parent, obj = obj, getattr(obj, part)
AttributeError: 'module' object has no attribute 'py'


What version of the product are you using? On what operating system?
Used both 0.4.2 and 0.4.1.  Ubuntu 8.04.  Python 2.5.2

Please provide any additional information below.

Works fine when I don't provide the extension:

(trunk)cburns@unittest2 15:11:53 $ unit2 test_example
...
----------------------------------------------------------------------
Ran 3 tests in 0.000s

OK

However, I rarely type out the full filename and instead use tab-completion.  
Is this a viable use case?  If so I'm willing to submit a patch.

Thanks!
Chris



```

Original issue reported on code.google.com by `chris.d....@gmail.com` on 7 Jun 2010 at 10:29

**Comment by GoogleCodeExporter** [comment]
```
So, supporting modules by default is required for backwards compatibility. 
*But*, checking if the name specified matches a file and using that if it does 
seems reasonable. I would accept a patch. Note that multiple module / filenames 
can be supplied at the command line.
```

Original comment by `fuzzyman` on 7 Jun 2010 at 10:32
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**

**Comment by GoogleCodeExporter** [comment]
```
This is done, *but* the filename should be checked *first* as otherwise if 
there is a foo module specifying foo.py can fail with "foo has no attribute 
.py".
```

Original comment by `fuzzyman` on 14 Aug 2010 at 9:45

**Comment by GoogleCodeExporter** [comment]
```
Hmm... don't think it is done actually. 
```

Original comment by `fuzzyman` on 27 Nov 2010 at 2:47

**Comment by GoogleCodeExporter** [comment]
```
Feature added to unittest in python 3.2 in revision 87003. Still needs porting 
to unittest2.

```

Original comment by `fuzzyman` on 4 Dec 2010 at 1:14
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
Need to verify it was included in the backports
```

Original comment by `robert.c...@gmail.com` on 5 Nov 2014 at 8:14

**Comment by GoogleCodeExporter** [comment]
```
This is fixed:

$ python -m unittest2.__main__ -v foo
test_foo (foo.F) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
(testtools-2.6)robertc@subunit-lucid:~/personal/testtools$ python -m 
unittest2.__main__ -v foo.py
test_foo (foo.F) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK

However it doesn't work with unit2, because that has a different PYTHONPATH:

$ PYTHONPATH=. unit2 -v foo
test_foo (foo.F) ... ok

----------------------------------------------------------------------
Ran 1 test in 0.000s

OK
(testtools-2.6)robertc@subunit-lucid:~/personal/testtools$ unit2 -v foo
foo (unittest2.loader.ModuleImportFailure) ... ERROR

======================================================================
ERROR: foo (unittest2.loader.ModuleImportFailure)
----------------------------------------------------------------------
ImportError: Failed to import test module: foo
Traceback (most recent call last):
  File "/home/robertc/.virtualenvs/testtools-2.6/lib/python2.6/site-packages/unittest2/loader.py", line 161, in loadTestsFromName
    module = __import__(module_name)
ImportError: No module named foo


----------------------------------------------------------------------
Ran 1 test in 0.001s

FAILED (errors=1)


This is a unittest2 specific issue, because there isn't a non-module CLI in 
cPython today.

I will file a bug about how it surfaces though.
```

Original comment by `robert.c...@gmail.com` on 7 Nov 2014 at 10:16

**Comment by GoogleCodeExporter** [comment]
```
Closing in favour of http://bugs.python.org/issue22814
```

Original comment by `robert.c...@gmail.com` on 7 Nov 2014 at 10:18
- Changed state: **Duplicate**
