### ISSUE TITLE
TestCase.assertDatetimeAlmostEqual

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/unittest-ext#19]
```
I have an enhancement for unittest2 - method that compares two datetime objects 
and pass when they are within timespan difference:


def assertDatetimeAlmostEqual(self, first, second, delta=None, msg=None):
    """Fail if the two datetime objects are unequal as determined by their
       timespan difference.
    """
    if first == second:
        # shortcut
        return
    if delta is None:
        delta = timedelta(seconds=5)
    if first < second and (second-first) <= delta:
        return
    elif first > second and (first-second) <= delta:
        return
    standardMsg = '%s != %s within %s delta' % (safe_repr(first),
                                                safe_repr(second),
                                                safe_repr(delta))
    msg = self._formatMessage(msg, standardMsg)
    raise self.failureException(msg)

```

Original issue reported on code.google.com by `lcenov...@gmail.com` on 8 Jun 2010 at 3:11

**Comment by GoogleCodeExporter** [comment]
```
This is already supported by the new delta keyword argument to 
assertAlmostEqual:

>>> from unittest2 import TestCase
>>> from datetime import *
>>> d1 = datetime.now()
>>> d2 = datetime.now()
>>> delta = timedelta(seconds=10)
>>> t = TestCase('assert_')
>>> t.assertAlmostEqual(d1, d2, delta=delta)
>>> delta = timedelta(seconds=1)
>>> t.assertAlmostEqual(d1, d2, delta=delta)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "unittest2/case.py", line 565, in assertAlmostEqual
    raise self.failureException(msg)
AssertionError: datetime.datetime(2010, 6, 8, 16, 17, 38, 657105) != 
datetime.datetime(2010, 6, 8, 16, 17, 43, 961265) within datetime.timedelta(0, 
1) delta
```

Original comment by `fuzzyman` on 8 Jun 2010 at 3:19
- Changed state: **WontFix**
- Added labels: **Type-Enhancement**
- Removed labels: **Type-Defect**
