### ISSUE TITLE
loading the JunitXml plugin causes an exception

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/unittest-ext#39]
```
What steps will reproduce the problem?
From a checkout of the plugins branch, run ./unit2 --junit-xml

What is the expected output? What do you see instead?

expected output is:

................................................................................
................................................................................
................................................................................
........................................
----------------------------------------------------------------------
Ran 280 tests in 0.870s


Actual output is:

Traceback (most recent call last):
  File "./unit2", line 7, in <module>
    main_()
  File "/home/aefalcon/src/unittest2/unittest2/main.py", line 436, in main_
    TestProgram(module=None)
  File "/home/aefalcon/src/unittest2/unittest2/main.py", line 151, in __init__
    self.parseArgs(argv)
  File "/home/aefalcon/src/unittest2/unittest2/main.py", line 176, in parseArgs
    options, args = self._parseArgs(argv[1:], forDiscovery=forDiscovery)
  File "/home/aefalcon/src/unittest2/unittest2/main.py", line 395, in _parseArgs
    hooks.pluginsLoaded(PluginsLoadedEvent())
  File "/home/aefalcon/src/unittest2/unittest2/events.py", line 281, in __call__
    result = handler(event)
TypeError: pluginsLoaded() takes exactly 1 argument (2 given)


What version of the product are you using? On what operating system?

unittest2-0.6.0.alpha
changeset 406:67d08c1573ea
running on Ubuntu 10.10


Please provide any additional information below.

The pluginsLoaded method of JunitXML is missing an events parameter.  A patch 
is attached.
```

Original issue reported on code.google.com by `aefal...@gmail.com` on 17 Nov 2010 at 8:19

Attachments:
- [junit-pluginsLoaded.patch](https://storage.googleapis.com/google-code-attachments/unittest-ext/issue-39/comment-0/junit-pluginsLoaded.patch)

**Comment by GoogleCodeExporter** [comment]
```
Plugins development will happen either in cpython or testtools depending on 
whether we come up with a stable or experimental API to start with.
```

Original comment by `robert.c...@gmail.com` on 7 Nov 2014 at 11:02
- Changed state: **WontFix**
