### ISSUE TITLE
Strangeness with @unittest2.skip

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/unittest-ext#64]
```
I'm getting some weird results while using unittest2 for testing my Python 2.6 
project.

For one, I get:
unittest2/case.py:326: DeprecationWarning: Use of a TestResult without an 
addSkip method is deprecated

...whenever I try to decorate my test methods with @unittest2.skip('Reason').  
Am I doing something wrong?

Secondly, I would expect @unittest2.skip('Reason') to make my test output show:
testSkippedMethod (project.blah.module) ... "skipped - Reason"

but instead, I get the usual "ok" printout, and the final "OK" line doesn't 
show anything about tests skipped.  Is that expected behavior for unittest2?

I'm using Eclipse Helios SR2 and PyDev 2.0.0 on OSX 10.6, using the MacPorts 
version of Python 2.6 (/opt/local/bin/python2.6).

I've tried using the unit2 script to run my tests, to take out the potential 
problems introduced by Eclipse and PyDev, but that fails, too!

$ unit2 -v ContactInfo
Traceback (most recent call last):
  File "/Users/robert/bin/unit2", line 9, in <module>
    load_entry_point('unittest2==0.5.1', 'console_scripts', 'unit2')()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/unittest2-0.5.1-py2.6.egg/unittest2/main.py", line 240, in main_
    main(module=None)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/unittest2-0.5.1-py2.6.egg/unittest2/main.py", line 97, in __init__
    self.parseArgs(argv)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/unittest2-0.5.1-py2.6.egg/unittest2/main.py", line 152, in parseArgs
    self.createTests()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/unittest2-0.5.1-py2.6.egg/unittest2/main.py", line 161, in createTests
    self.module)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/unittest2-0.5.1-py2.6.egg/unittest2/loader.py", line 148, in loadTestsFromNames
    suites = [self.loadTestsFromName(name, module) for name in names]
  File "/opt/local/Library/Frameworks/Python.framework/Versions/2.6/lib/python2.6/site-packages/unittest2-0.5.1-py2.6.egg/unittest2/loader.py", line 111, in loadTestsFromName
    module = __import__('.'.join(parts_copy))
ImportError: No module named ContactInfo


At first I thought it might be because unit2 was using the wrong version of 
Python, but I tweaked to script to ensure it's using the right python2.6 
install, and I get the same error.
```

Original issue reported on code.google.com by `coredump...@gmail.com` on 20 May 2011 at 11:06

**Comment by GoogleCodeExporter** [comment]
```
The first error message "DeprecationWarning: Use of a TestResult without an 
addSkip method is deprecated" explains the problem - the test suite is being 
run with a TestResult object that doesn't have the addSkip method. This method 
is on the unittest2.TestResult but not on the TestResult from older versions of 
Python. This is why your skips are not being reported - TestResult.addSkip is 
how unittest2 collects and reports skips. Without this method it falls back to 
reporting them as passes.

"unit2 -v ContactInfo" is telling unittest2 to run tests in a *module* called 
ContactInfo. Do you intend it to run tests in a *class* called ContactInfo? If 
you have a module called ContactInfo then unit2 can't import it from the 
directory it is being run in. What happens if you start a python interactive 
interpreter in that directory and do "import ContactInfo"?
```

Original comment by `fuzzyman` on 23 May 2011 at 11:43

**Comment by GoogleCodeExporter** [comment]
```
Thanks for the answer about the TestResult; the error message doesn't make it 
clear that it's happening because my Python version is too low. If anything, a 
DeprecationWarning makes it seem like my Python version is too *high*.

I found out that I can make use of unittest2.TestResult by using:
if __name__ == '__main__':
    unittest2.main(verbosity=2)

However, my code shop uses Pydev's "Run as Python unit-test" to test our code, 
which appears to ignore any existing "if __name__ == '__main__':" block and run 
the usual unittest.main() function, instead.  Or something like that.

So, I'm wondering if there's any way to tell my test code to use 
unittest2.TestResult, even when it's run by PyDev's test runner?
```

Original comment by `coredump...@gmail.com` on 24 May 2011 at 5:01

**Comment by GoogleCodeExporter** [comment]
```
A DeprecationWarning always means something is old, but I guess in your case 
there is room for confusion about which bit was the old bit.

I'm afraid I've no idea how to get pydev to use the unittest2 test runner / 
test result. You'll have to ask pydev support or on the pydev mailing list.
```

Original comment by `fuzzyman` on 24 May 2011 at 6:11
- Changed state: **Invalid**

**Comment by GoogleCodeExporter** [comment]
```
I talked to the pydev folks, and they recognized that their particular testing 
system doesn't properly support unittest2.  So, I posted a feature request to 
add support (and their suggestion).  Hopefully that will be added soon.
```

Original comment by `coredump...@gmail.com` on 25 May 2011 at 10:40

**Comment by GoogleCodeExporter** [comment]
```
Cool - thanks.
```

Original comment by `fuzzyman` on 26 May 2011 at 5:05
