### ISSUE TITLE
If you raise a string (in 2.4), unittest2.main will just stop.

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/unittest-ext#70]
```
What steps will reproduce the problem?

In Python 2.4, run the following code:

import unittest2

class Test(unittest2.TestCase):
    def test1(self):
      raise "Not an Exception"

    def test2(self):
      self.assertTrue(True)

if __name__ == "__main__":
    unittest2.main()

What is the expected output? What do you see instead?

Traceback (most recent call last):
  File "test.py", line 11, in ?
    unittest2.main()
  File "/home/szopa/tmp/unittest2/main.py", line 98, in __init__
    self.runTests()
  File "/home/szopa/tmp/unittest2/main.py", line 232, in runTests
    self.result = testRunner.run(self.test)
  File "/home/szopa/tmp/unittest2/runner.py", line 162, in run
    test(result)
  File "/home/szopa/tmp/unittest2/suite.py", line 64, in __call__
    return self.run(*args, **kwds)
  File "/home/szopa/tmp/unittest2/suite.py", line 84, in run
    self._wrapped_run(result)
  File "/home/szopa/tmp/unittest2/suite.py", line 114, in _wrapped_run
    test._wrapped_run(result, debug)
  File "/home/szopa/tmp/unittest2/suite.py", line 116, in _wrapped_run
    test(result)
  File "/home/szopa/tmp/unittest2/case.py", line 398, in __call__
    return self.run(*args, **kwds)
  File "/home/szopa/tmp/unittest2/case.py", line 340, in run
    testMethod()
  File "test.py", line 5, in test1
    raise "Not an Exception"
Not an Exception

I would like to see something like

E.
======================================================================
ERROR: test1 (__main__.Test)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "test.py", line 5, in test1
    raise Exception("Not an Exception")
Exception: Not an Exception

----------------------------------------------------------------------
Ran 2 tests in 0.001s

FAILED (errors=1)

What version of the product are you using? On what operating system?


Please provide any additional information below.

In Python 2.4 it is still legal to raise a string instead of an exception... 
And, apparently, unittest2 at some points checks for Exception explicitly.



```

Original issue reported on code.google.com by `sz...@google.com` on 21 Dec 2011 at 11:37

**Comment by GoogleCodeExporter** [comment]
```
This can be easily changed in the unittest2 code, by adding an additional 
(catch-all) except: block.

E.g. in the TestCase.run method, I changed (around line 340 in case.py)

try:
    testMethod()
...
except:
    result.addError(self, sys.exc_info())
...

and I've also added this exception catcher around the setUp and tearDown (lines 
~360) method calls.

I'm running 2.5.2 and I also ran into this issue with unittest2 (a library we 
don't control still throws string exceptions).
```

Original comment by `joostvan...@gmail.com` on 1 Nov 2012 at 12:58

**Comment by GoogleCodeExporter** [comment]
```
We no longer support python < 2.6
```

Original comment by `robert.c...@gmail.com` on 4 Nov 2014 at 3:09
- Changed state: **WontFix**
