### ISSUE TITLE
"from unittest2 import FunctionTestClass" and "unittest2.collector" are incompatible

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/unittest-ext#71]
```
If, in your test module, you use:

from unittest2 import FunctionTestClass

And then try to use:

test_suite='unittest2.collector'

in setuptools.setup, you get a completely obscure error:


Traceback (most recent call last):
  File "setup.py", line 34, in <module>
    test_suite='unittest2.collector',
  File "/usr/local/Cellar/python/2.7.2/lib/python2.7/distutils/core.py", line 152, in setup
    dist.run_commands()
  [...snip...]
  File "/usr/local/Cellar/python/2.7.2/lib/python2.7/unittest/runner.py", line 53, in startTest
    self.stream.write(self.getDescription(test))
  File "/usr/local/Cellar/python/2.7.2/lib/python2.7/unittest/runner.py", line 46, in getDescription
    return '\n'.join((str(test), doc_first_line))
  File "~/pythons/test/lib/python2.7/site-packages/unittest2/case.py", line 1074, in __str__
    self._testFunc.__name__)
AttributeError: 'str' object has no attribute '__name__'

The problem is loader.TestLoader.loadTestsFromTestCase thinks the imported 
FunctionTestCase class is a valid test case because it has defined a runTest. 
When the test cases are created, it is done by instantiating new 
FunctionTestCase instances, passing them the string 'runTest'. FunctionTestCase 
expects its constructor to take a function, so it treats it as such. 

Much later on, when everything is expecting a test function, the string that 
was passed to the FunctionTestCase constructor fails to behave like a function 
(obviously) and we get the afore-mentioned AttributeError.

There are two problems here:

First, TestLoader.loadTestsFromTestCase should not instantiate new test cases 
if the test case is a FunctionTestCase. By definition, FunctionTestCase wraps a 
single function, unlike other TestCase subclasses.

Second (and this would solve the first), the actual types for FunctionTestCase 
and TestCase should probably be ignored (This is, of coure, my own opinion).  
There may be some extreme cases where people have done acrobatics to create 
TestCases without subclassing TestCase, but the intention of the API is to 
subclass.

Alternatively, it should be made explicitly clear that "from unittest2 import 
XXX" is a very bad idea.  That seems very unpythonic, though.
```

Original issue reported on code.google.com by `travis.j...@gmail.com` on 21 Feb 2012 at 8:05

**Comment by GoogleCodeExporter** [comment]
```
Wow, thanks for reporting this. I expect that vanilla unittest has the same 
issue.
```

Original comment by `fuzzyman` on 21 Feb 2012 at 10:55

**Comment by GoogleCodeExporter** [comment]
Original comment by `robert.c...@gmail.com` on 4 Nov 2014 at 3:06
- Changed state: **Accepted**

**Comment by GoogleCodeExporter** [comment]
```
See http://bugs.python.org/issue22680
```

Original comment by `robert.c...@gmail.com` on 4 Nov 2014 at 3:10

**Comment by rbtcollins** [comment]
Now http://bugs.python.org/issue14534. Closing this in favour of the upstream bug.
