### ISSUE TITLE
Pull CPython sources from Mercurial (hg) instead of Subversion (svn)

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/unittest-ext#80]
```
Maybe there's already an issue for this somewhere, but I couldn't find it.

I noticed that MarkRoddy created a branch for this, so I thought it should have 
an issue to track it so that his work doesn't go to waste:

https://code.google.com/p/unittest-ext/source/browse/?name=UsePythonMercurialRep
o

Perhaps at some point this should be merged to the "default" branch?
```

Original issue reported on code.google.com by `msabr...@gmail.com` on 5 May 2014 at 5:25

**Comment by GoogleCodeExporter** [comment]
```
Right now it's not working though because __version__ isn't present for 
unittest in CPython.

$ fab create_lib
...
[localhost] local: rm -rf unittest2
[localhost] local: touch unittest2/compatibility.py
[localhost] local: cat unittest2-py3k.patch|patch -p0 --no-backup-if-mismatch

Done.

$ tox
...
GLOB sdist-make: /Users/marca/dev/hg-repos/unittest-ext/unittest2py3k/setup.py
ERROR: invocation failed, logfile: 
/Users/marca/dev/hg-repos/unittest-ext/unittest2py3k/.tox/log/tox-0.log
ERROR: actionid=tox
msg=packaging
cmdargs=['/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app
/Contents/MacOS/Python', 
local('/Users/marca/dev/hg-repos/unittest-ext/unittest2py3k/setup.py'), 
'sdist', '--formats=zip', '--dist-dir', 
local('/Users/marca/dev/hg-repos/unittest-ext/unittest2py3k/.tox/dist')]
env=None
Traceback (most recent call last):
  File "setup.py", line 12, in <module>
    from unittest2 import __version__ as VERSION
ImportError: cannot import name __version__

ERROR: FAIL could not package project

Not sure where it should get VERSION from now.
```

Original comment by `msabr...@gmail.com` on 5 May 2014 at 6:37

**Comment by GoogleCodeExporter** [comment]
```
Hmmm I might've done something wrong before (maybe I didn't clean out my 
directory properly?), because just now I did it again and I did get the error 
about __version__.

```

$ hg clone https://code.google.com/p/unittest-ext/
...
$ cd unittest-ext
$ hg update UsePythonMercurialRepo
...
$ hg log -r .
changeset:   108:82c59a8e44d8
branch:      UsePythonMercurialRepo
tag:         tip
user:        Mark Roddy markroddy@gmail.com
date:        Sun Mar 27 16:55:15 2011 -0400
files:       unittest2py3k/hg-cpython.ini
description:
Set the revision attribute to the revision I've been successfully running 
against.
$ cd cd unittest2py3k
$ fab create_lib
...
$ tox -e py32,py33
❯ tox -e py32,py33
GLOB sdist-make: /private/tmp/unittest-ext/unittest2py3k/setup.py
py32 create: /private/tmp/unittest-ext/unittest2py3k/.tox/py32
py32 inst: 
/private/tmp/unittest-ext/unittest2py3k/.tox/dist/unittest2py3k-0.5.1.zip
py32 runtests: commands[0] | python unit2.py discover
................................................................................
................................................................................
................................................................................

## ...............................................................

Ran 303 tests in 0.384s

OK
py33 create: /private/tmp/unittest-ext/unittest2py3k/.tox/py33
py33 inst: 
/private/tmp/unittest-ext/unittest2py3k/.tox/dist/unittest2py3k-0.5.1.zip
py33 runtests: commands[0] | python unit2.py discover
................................................................................
........................................................................F.......
...........F....................................................................

# ...............................................................

FAIL: test_loadTestsFromName__unknown_module_name 

## (unittest2.test.test_loader.Test_TestLoader)

Traceback (most recent call last):
  File "/private/tmp/unittest-ext/unittest2py3k/unittest2/test/test_loader.py", line 240, in test_loadTestsFromName__unknown_module_name
    loader.loadTestsFromName('sdasfasfasdf')
ImportError: No module named 'sdasfasfasdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/unittest-ext/unittest2py3k/unittest2/test/test_loader.py", line 242, in test_loadTestsFromName__unknown_module_name
    self.assertEqual(str(e), "No module named sdasfasfasdf")
AssertionError: "No module named 'sdasfasfasdf'" != 'No module named 
sdasfasfasdf'
- No module named 'sdasfasfasdf'
  ?                 -            -
- No module named sdasfasfasdf

# 

FAIL: test_loadTestsFromNames__unknown_module_name 

## (unittest2.test.test_loader.Test_TestLoader)

Traceback (most recent call last):
  File "/private/tmp/unittest-ext/unittest2py3k/unittest2/test/test_loader.py", line 620, in test_loadTestsFromNames__unknown_module_name
    loader.loadTestsFromNames(['sdasfasfasdf'])
ImportError: No module named 'sdasfasfasdf'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/unittest-ext/unittest2py3k/unittest2/test/test_loader.py", line 622, in test_loadTestsFromNames__unknown_module_name
    self.assertEqual(str(e), "No module named sdasfasfasdf")
AssertionError: "No module named 'sdasfasfasdf'" != 'No module named 
sdasfasfasdf'
- No module named 'sdasfasfasdf'
  ?                 -            -
- No module named sdasfasfasdf

---

Ran 303 tests in 0.487s

FAILED (failures=2)
ERROR: InvocationError: 
'/private/tmp/unittest-ext/unittest2py3k/.tox/py33/bin/python unit2.py discover'

---

---

summary 

---

---

  py32: commands succeeded
ERROR:   py33: commands failed

```

The py33 failure is fixed by my patch in 
https://code.google.com/p/unittest-ext/issues/detail?id=65

See: 
https://code.google.com/r/msabramo-unittest-ext/source/detail?r=a5fc00d8b6903893
5148af5af71dd929fe4f73aa&name=UsePythonMercurialRepo


```

Original comment by `msabr...@gmail.com` on 5 May 2014 at 8:56

**Comment by GoogleCodeExporter** [comment]
```
MarkRoddy also has a repo on Bitbucket I just noticed:

https://bitbucket.org/markroddy/unittest2-py3k-patch
```

Original comment by `msabr...@gmail.com` on 6 May 2014 at 5:44

**Comment by GoogleCodeExporter** [comment]
```
I think this can be closed because we now have a single tree and a transplant 
script for backporting from cPython.
```

Original comment by `robert.c...@gmail.com` on 4 Nov 2014 at 2:56
- Changed state: **Fixed**
