### ISSUE TITLE
unittest 0.7.0 fails when previous versions worked

### ISSUE THREAD

**Issue by GoogleCodeExporter** [testing-cabal/unittest-ext#83]
```
What steps will reproduce the problem?
1. download pywikibot (git clone https://gerrit.wikimedia.org/r/pywikibot/core)
2. python2.6 setup.py test

What is the expected output?
Normal test run:
https://travis-ci.org/wikimedia/pywikibot-core/jobs/39430205

What do you see instead?

Traceback (most recent call last):
  File "setup.py", line 141, in <module>
    use_2to3=False
  File "/opt/python/2.6.9/lib/python2.6/distutils/core.py", line 152, in setup
    dist.run_commands()
  File "/opt/python/2.6.9/lib/python2.6/distutils/dist.py", line 975, in run_commands
    self.run_command(cmd)
  File "/opt/python/2.6.9/lib/python2.6/distutils/dist.py", line 995, in run_command
    cmd_obj.run()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/setuptools/command/test.py", line 138, in run
    self.with_project_on_sys_path(self.run_tests)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/setuptools/command/test.py", line 118, in with_project_on_sys_path
    func()
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/setuptools/command/test.py", line 164, in run_tests
    testLoader = cks
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/unittest2/main.py", line 67, in __init__
    self.parseArgs(argv)
  File "/home/travis/virtualenv/python2.6.9/lib/python2.6/site-packages/unittest2/main.py", line 102, in parseArgs
    self.testNames = _convert_names(self.tests)
NameError: global name '_convert_names' is not defined

https://travis-ci.org/wikimedia/pywikibot-core/jobs/39559641

What version of the product are you using? On what operating system?
Ubuntu

```

Original issue reported on code.google.com by `jay...@gmail.com` on 31 Oct 2014 at 4:39

**Comment by GoogleCodeExporter** [comment]
```
Oh joy, this is fun. 0.7.1 coming shortly. There's also a weirdness with the 
new unit2 stuff I'm going to address

```

Original comment by `robert.c...@gmail.com` on 31 Oct 2014 at 5:48

**Comment by GoogleCodeExporter** [comment]
```
Please let me know if 0.7.1 is really fixed (it should be :)). I can't close 
the issue - hopefully I'll get access to do so soon!
```

Original comment by `robert.c...@gmail.com` on 31 Oct 2014 at 6:44

**Comment by GoogleCodeExporter** [comment]
```
yup; it is fixed!  makasih!

I cant close this issue either, but I've closed the pywikibot bug 
(https://bugzilla.wikimedia.org/show_bug.cgi?id=72801).
```

Original comment by `jay...@gmail.com` on 31 Oct 2014 at 7:24

**Comment by GoogleCodeExporter** [comment]
Original comment by `fuzzyman` on 31 Oct 2014 at 11:25
- Changed state: **Fixed**
